name: Dusk test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: Run Dusk Test
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome

    steps:
      - uses: actions/checkout@v2

      - run: php artisan dusk:chrome-driver
        env:
          BROWSER: chrome

      - run: php artisan dusk
        env:
          BROWSER: chrome

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: screenshots/

# fin
